#!/bin/bash
exec 2>&1

if [ ! -f /usr/local/ZebraNetworkSystems/NeoRouter/nrserver.README ]; then
  dpkg -i /$NRSERVER_DEB_NAME
fi

PID=`cat /var/run/nrserver.pid`

if ps -p $PID > /dev/null ; then
  sleep 10
else
  exec /etc/init.d/nrserver.sh start
fi
